-- AlterEnum
ALTER TYPE "TableShape" ADD VALUE 'RECTANGLE';

-- AlterTable
ALTER TABLE "table" ADD COLUMN "rotation" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "width" DOUBLE PRECISION,
ADD COLUMN "height" DOUBLE PRECISION,
ADD COLUMN "chairsTop" INTEGER,
ADD COLUMN "chairsRight" INTEGER,
ADD COLUMN "chairsBottom" INTEGER,
ADD COLUMN "chairsLeft" INTEGER;
